# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: updater.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'updater.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rupdater.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x0bVersionInfo\x12\x10\n\x08\x64ir_name\x18\x01 \x01(\t\x12\x11\n\tbuild_tag\x18\x02 \x01(\t\x12\x14\n\x0cversion_name\x18\x03 \x01(\t\"5\n\x13GetVersionsResponse\x12\x1e\n\x08versions\x18\x01 \x03(\x0b\x32\x0c.VersionInfo2R\n\nUpdaterApp\x12\x44\n\x14GetAvailableVersions\x12\x16.google.protobuf.Empty\x1a\x14.GetVersionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'updater_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONINFO']._serialized_start=46
  _globals['_VERSIONINFO']._serialized_end=118
  _globals['_GETVERSIONSRESPONSE']._serialized_start=120
  _globals['_GETVERSIONSRESPONSE']._serialized_end=173
  _globals['_UPDATERAPP']._serialized_start=175
  _globals['_UPDATERAPP']._serialized_end=257
# @@protoc_insertion_point(module_scope)
